version: '3.9'

services:
  db-inventory:
    container_name: db-inventory
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431


  db-orders:
    container_name: db-orders
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_DB: ms_orders
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
    expose:
      - 3307
    command: --port=3307

  ### Posgres database for Products
  db-products:
    container_name: db-products
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Posgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HTTP_PORT: 8181
        DB_VENDOR: POSTGRES
        DB_ADDR: db-keycloak
        DB_PORT: 5433
        DB_DATABASE: db_keycloak
        DB_USER: postgres
        DB_PASSWORD: sasa1234
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak

