version: '3.9'

services:
  db-inventory:
    container_name: db-inventory
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431


  db-orders:
    container_name: db-orders
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_DB: ms_orders
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
    expose:
      - 3307
    command: --port=3307

  ### Posgres database for Products
  db-products:
    container_name: db-products
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa1234
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432



